---
- hosts: myserver
  become: true
  vars:
    - vars/default.yml
- tasks:
  - name: Install latest version of Apache
    apt:
      name: nginx
      update_cache: yes
      state: latest


  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted