---
- hosts: web
  become: true
  vars:
    - vars/default.yml
- tasks:
  - name: Install latest version of Nginx
    apt:
      name: nginx
      update_cache: yes
      state: latest

  - name: Adjusting the Firewall
    ufw:
      rule: allow
      port: {{ http_port }}
      protoclol: tcp

  - name: Setting Up Server Blocks
    file:
      path: "/var/www/{{ http_host }}/html"
      state: directory
      owner: "{{ app_user }}"
      mode: '0755'

  - name: Copy your index page
    template:
      src: "files/index.html.j2"
      dest: "/var/www/{{ http_host }}/html/index.html"

  - name: Set up virtuahHost
    template:
      src: "files/nginx.conf.j2"
      dest: "/etc/nginx/sites-available/{{ http_conf }}"
    notify: restart-nginx

  - name: Enable new site
    file:
      src: /etc/nginx/sites-available/
      dest: /etc/nginx/sites-enabled/
      state: link
    notify: restart-nginx

handlers:
  - name: restart-nginx
    service:
      name: nginx
      state: restarted