---
- hosts: test
  become: true
  become_user: datnt
  vars:
    - vars/default.yml
  tasks:
  - name: Create document root for your domain
    file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: "{{ app_user }}"
      mode: '0755'
  - name: Copy your index page
    template:
      src: "files/index.html.j2"
      dest: "/var/www/{{ http_host }}/index.html"
  - name: Set up virtuahHost
    template:
      src: "files/apache.conf.j2"
      dest: "/etc/apache2/sites-available/{{ http_conf }}"
    notify: Restart Apache
  - name: Enable new site
    shell: /usr/sbin/a2ensite {{ http_conf }}
    notify: Reload Apache
  - name: Disable default Apache site
    shell: /usr/sbin/a2dissite 000-default.conf
    when: disable_default
    notify: Reload Apache
  - name: X-XSS-Protection
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header set X-XSS-Protection "1; mode=block"
    notify: Restart Apache
  - name: HTTP Strict Transport Security
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header     set    Strict-Transport-Security  "max-age=31536000;includeSubDomains; preload"
    notify: Restart Apache
  - name: X-Frame-Options
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header always append X-Frame-Options DENY
    notify: Restart Apache
  - name: X-Content-Type-Options
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header set X-Content-Type-Options nosniff
    notify: Restart Apache
  - name: Content Security Policy
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header set Content-Security-Policy "default-src 'self';"
    notify: Restart Apache
  - name: xxx
    blockinfile:
      path: /tmp/ssh_config
      block: |
        ServerSignature Off
        ServerTokens Prod
    notify: Restart Apache
  handlers:
  - name: Restart Apache
    service:
      name: apache2
      state: restarted
  - name: Reload Apache
    service:
      name: apache2
      state: reloaded