---
- hosts: test
  become: true
  become_user: datnt
  vars:
    - vars/default.yml
  tasks:
  - name: Create document root for your domain
    file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: "{{ app_user }}"
      mode: '0755'
  - name: Copy your index page
    template:
      src: "files/index.html.j2"
      dest: "/var/www/{{ http_host }}/index.html"
  - name: Set up virtuahHost
    template:
      src: "files/apache.conf.j2"
      dest: "/etc/apache2/sites-available/{{ http_conf }}"
    notify: restart-apache
  handlers:
  - name: restart-apache
    service:
      name: apache2
      state: restarted