---
- hosts: test
  # become: true
  tasks:
  - name: Check OS
    command: cat /proc/version
    register: os_info
  - debug: os_info.stdout_lines

  - name: FREE AND USED MEMORY
    command: free -h
    register: mem_info
  - debug: mem_info.stdout_lines

  - name: FILE SYSTEM DISK SPACE USAGE
    command: df
    register: disk_info
  - debug: disk_info.stdout_lines