---
- hosts: web
  become: yes
  vars:
    - vars/default.yml
- tasks:
  - name: Install software-properties-common
    apt: 
      name: software-properties-common
      update_cache: yes 
      state: latest

  - name: Repo PHP 7.4
    apt_repository:
      repo="ppa:ondrej/php"

  - name: Install PHP7.4
    apt: 
      name: php7.4
      update_cache: yes 
      state: present

  - name: Install package
    apt: 
      name: {{ item }}
      update_cache: yes 
      state: present
    with_item:
      - php7.4-cli
      - php7.4-json
      - php7.4-common
      - php7.4-mysql
      - php7.4-zip
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-curl
      - php7.4-xml
      - php7.4-bcmath
