---
- hosts: myserver
  become: yes
  vars:
    - vars/default.yml
- tasks:
  - name: Install software-properties-common
    apt: 
      name: software-properties-common
      update_cache: yes 
      state: latest

  - name: Install PHP
    apt: 
      name: php
      update_cache: yes 
      state: latest

  - name: Install package
    apt: 
      name: {{ item }}
      update_cache: yes 
      state: latest
    with_item:
      - php7.4-cli
      - php7.4-json
      - php7.4-common
      - php7.4-mysql
      - php7.4-zip
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-curl
      - php7.4-xml
      - php7.4-bcmath
