---
- hosts: web
  become: yes
  tasks:
  - name: Install MySQL
    apt: name=mysql-server update_cache=yes  state=lastest

  - name: Ensure mysql service is running
    systemd:
      name: mysql
      state: started
      enabled: yes