---
- hosts: test
  become: true
- tasks:
  - name: X-XSS-Protection
    lineinfile:
      path: /etc/nginx/sites-available/default
      insertafter: "try_file*"
      line: add_header X-XSS-Protection "1; mode=block";
    notify: Restart Nginx
  - name: HTTP Strict Transport Security
    lineinfile:
      path: /etc/nginx/sites-available/default
      insertafter: "try_file*"
      line: add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    notify: Restart Nginx
  - name: X-Frame-Options
    lineinfile:
      path: /etc/nginx/sites-available/default
      insertafter: "try_file*"
      line: add_header X-Frame-Options "DENY";
    notify: Restart Nginx
  - name: X-Content-Type-Options
    lineinfile:
      path: /etc/nginx/sites-available/default
      insertafter: "try_file*"
      line: add_header X-Content-Type-Options nosniff;
    notify: Restart Nginx
  - name: Content Security Policy
    lineinfile:
      path: /etc/nginx/sites-available/default
      insertafter: "try_file*"
      line: add_header Content-Security-Policy "default-src 'self'";
    notify: Restart Nginx
  handlers:
  - name: Restart Nginx
    service:
      name: nginx
      state: restarted