---
- hosts: test
  become: true
- tasks:
  - name: Config file /etc/pam.d/common-password if OS is Debian.
    lineinfile: 
      path: /etc/pam.d/common-password
      line:
        password requisite pam_cracklib.so try_first_pass retry=3 minlength=12 lcredit=1 ucredit=1 dcredit=1 ocredit=1 difok=4
    when: ansible_facts['os_family'] == "Debian"
  - name: Config file /etc/pam.d/system-auth  if OS is RedHat.
    lineinfile:
      path: /etc/pam.d/system-auth
      line:
        password requisite pam_cracklib.so try_first_pass retry=3
    when: ansible_facts['os_family'] == "RedHat"
  - name: Config Password Authentication
    lineinfile:
      path: /etc/ssh/sshd_config
      line:
        Password Authentication no
  - name: config PermitRootLogin
    replace:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin.*'
      replace: "PermitRootLogin no"
  - name: Set minimum number of days between password changes
    replace:
      path: /etc/login.defs
      regexp: 'PASS_MIN_DAYS.*'
      replace: "PASS_MIN_DAYS 6"