---
- hosts: test
  become: true
  become_user: datnt
- tasks:
  - name: Config file /etc/pam.d/common-password if OS is Debian.
    lineinfile:
      path: /etc/pam.d/common-password 
      line: password   requisite   pam_cracklib.so   try_first_pass   retry=3 minlength=12 lcredit=1 ucredit=1 dcredit=1 ocredit=1 difok=4
      when: ansible_facts['os_family'] == "Debian"
  - name: Config file /etc/pam.d/system-auth  if OS is RedHat.
    lineinfile:
      path: /etc/pam.d/system-auth  
      line: password    requisite     pam_cracklib.so try_first_pass retry=3
      when: ansible_facts['os_family'] == "RedHat"
  
  - name: abc
    lineinfile:
      path: /home/datnt/test/test.txt
      line: demo