---
- hosts: test
  become: true
  become_user: datnt
- tasks:
  - name: Config file /etc/pam.d/common-password if OS is Debian.
    shell: echo "password   requisite   pam_cracklib.so   try_first_pass   retry=3 minlength=12 lcredit=1 ucredit=1 dcredit=1 ocredit=1 difok=4" >> /etc/pam.d/common-password
    when: ansible_facts['os_family'] == "Debian"
  - name: Config file /etc/pam.d/system-auth  if OS is RedHat.
    shell: echo "password    requisite     pam_cracklib.so try_first_pass retry=3" >> /etc/pam.d/system-auth
    when: ansible_facts['os_family'] == "RedHat"