---
- hosts: test
  become: true
  tasks:
  - name: Create folder /var/log/users_history/
    file:
      path: /var/log/users_history/
      state: directory
  - name: Grant Permission for new folder
    shell: chmod +t /var/log/users_history/
  - name: Create file shell and grant permission for new shell 
    file:
      path: /etc/profile.d/users_history.sh
      state: touch
      mode: 0770
  - name: Config shell
    blockinfile:
      path: /etc/profile.d/users_history.sh
      block: |
        _fuck=$(who am i|awk '{print $1}')
        _dis=$(id -u $_fuck)
        if (( $_dis > 0 ))
        then
        export HISTSIZE=10000
        export HISTTIMEFORMAT='%F %T'
        export HISTFILE=/var/log/users_history/history-users-$(who am I | awk '{print $1}';exit)-$(date +%F)
        export PROMPT_COMMAND='history -a'
        fi
  - name: source /etc/profile.d/users_history.sh
    script: /etc/profile.d/users_history.sh