---
- hosts: test
  become: true
  tasks:
  - name: Get package information
    package_facts:
      manager: "auto"
  - name: "Apache result"
    debug:
      msg: "Apache found"
    when: 
      - ansible_facts['os_family'] == "RedHat"
      - "'httpd' in ansible_facts.packages"
  - name: "Apache result"
    debug:
      msg: "Apache found"
    when: 
      - ansible_facts['os_family'] == "Debian"
      - "'apache2' in ansible_facts.packages"
  - name: "Nginx result"
    debug:
        msg: "Nginx found"
    when: "'nginx' in ansible_facts.packages"