---
- hosts: test
  become: true
  vars_files:
    - config.yaml
  tasks:
  - name: check file /etc/pam.d/common-password if OS is Debian
    shell: echo /etc/pam.d/common-password | grep "^password   requisite   pam_cracklib.so   try_first_pass   retry=3 minlength=12 lcredit=1 ucredit=1 dcredit=1 ocredit=1 difok=4"
    when: ansible_facts['os_family'] == "Debian"
    register: commond-password
  - name: if configuarated
    debug:
      msg: "file /etc/pam.d/common-password is configuarated"
    when: commond-password == common-password_debian
  - name: if not configuarated
    debug:
      msg: "file /etc/pam.d/common-password isn't configuarated"
    when: commond-password != common-password_debian

  - name: check file /etc/pam.d/system-auth  if OS is RedHat
    shell: echo /etc/pam.d/system-auth | grep "^password    requisite     pam_cracklib.so try_first_pass retry=3"
    when: ansible_facts['os_family'] == "RedHat"
    register: system-auth
  - name: if configuarated
    debug:
      msg: "file /etc/pam.d/system-auth is configuarated"
    when: system-auth == system-auth_redhat
  - name: if not configuarated
    debug:
      msg: "file /etc/pam.d/system-auth isn't configuarated"
    when: system-auth != system-auth_redhat

  - name: check config Password Authentication
    shell: cat /etc/ssh/sshd_config | grep "^Password Authentication no"
    register: config_password_authentication
  - name: Result check config Password Authentication
    debug:
      msg: "Password Authentication is configured"
    when: config_password_authentication == password_authentication

  - name: check config PermitRootLogin
    shell: cat /etc/ssh/sshd_config | grep "^PermitRootLogin.*"
    register: config_permitrootlogin
  - name: Result check config PermitRootLogin
    debug:
      msg: "PermitRootLogin is configured"
    when: config_permitrootlogin == permit_root_login