---
- hosts: test
  remote_user: root
  vars:
    - package: sudo
  tasks:
  - name: Get package information
    package_facts:
      manager: "auto"
  - name: Check Package Sudo is installed or not
    debug:
      msg: "Sudo is installed"
    when: "'sudo' in ansible_facts.packages"
  - name: Check Package Sudo is installed or not
    debug:
      msg: "Sudo isn't installed"
    when: "'sudo' not in ansible_facts.packages"