---
- hosts: web
  become: yes
  vars:
    - vars/default.yml
- tasks:

  - name: Install MySQL
    apt: 
      name: mysql-server
      update_cache: yes 
      state: lastest

  - name: Ensure mysql service is running
    systemd:
      name: mysqld
      state: started
      enabled: yes