---
- hosts: test
  become: true
  tasks:
  - name: Enable mod header
    shell: /usr/sbin/a2enmod headers
    notify: restart apache
  - name: X-XSS-Protection
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header set X-XSS-Protection "1; mode=block"
    notify: restart apache
  - name: HTTP Strict Transport Security
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header     set    Strict-Transport-Security  "max-age=31536000;includeSubDomains; preload"
    notify: restart apache
  - name: X-Frame-Options
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header always append X-Frame-Options DENY
    notify: restart apache
  - name: X-Content-Type-Options
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header set X-Content-Type-Options nosniff
    notify: restart apache
  - name: Content Security Policy
    lineinfile:
      path: /etc/apache2/apache2.conf
      line: Header set Content-Security-Policy "default-src 'self';"
    notify: restart apache
  - name: ServerSignature
    replace:
      path: /etc/apache2/conf-available/security.conf
      regexp: 'ServerSignature.*'
      replace: "ServerSignature Off"
  - name: ServerTokens
    replace:
      path: /etc/apache2/conf-available/security.conf
      regexp: 'ServerTokens.*'
      replace: "ServerTokens Prod"
    notify: restart apache
  handlers:
  - name: restart apache
    service:
      name: apache2
      state: restarted